---

- hosts:  testserver
  remote_user: ibiadmin
  become: true
  tasks:
  - name: "build docker image"
    docker_image: 
        name: custonginx
        path: docker
        state: present

  - name: "launch_container"
    docker_container: 
        name: custocontainer
        image: custonginx
        state: started
        ports: 
          - "9088:80"
